export const routeSegments = {
  auth: "auth",
  quotePublic: "quote",
  dashboard: "dashboard",
  deliveries: "deliveries",
  billing: "billing",
  quotes: "quotes",
  money: "money",
  products: "products",
  inventory: "inventory",
  sales: "sales",
  movements: "movements",
  expenses: "expenses",
  customers: "customers",
  suppliers: "suppliers",
  employees: "employees",
  reports: "reports",
  settings: "settings",
} as const;

export const routePaths = {
  auth: `/${routeSegments.auth}`,
  quotePublic: `/${routeSegments.quotePublic}`,
  dashboard: `/${routeSegments.dashboard}`,
  deliveries: `/${routeSegments.deliveries}`,
  billing: `/${routeSegments.billing}`,
  quotes: `/${routeSegments.quotes}`,
  quoteNew: `/${routeSegments.quotes}/new`,
  quoteNewProducts: `/${routeSegments.quotes}/new/products`,
  quoteNewFree: `/${routeSegments.quotes}/new/free`,
  money: `/${routeSegments.money}`,
  products: `/${routeSegments.products}`,
  inventory: `/${routeSegments.inventory}`,
  sales: `/${routeSegments.sales}`,
  movements: `/${routeSegments.movements}`,
  expenses: `/${routeSegments.expenses}`,
  customers: `/${routeSegments.customers}`,
  suppliers: `/${routeSegments.suppliers}`,
  employees: `/${routeSegments.employees}`,
  reports: `/${routeSegments.reports}`,
  settings: `/${routeSegments.settings}`,
} as const;
